/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ShopItemBean } from './model';
import { customInstance } from '../boot/axios';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const getItems = (options?: SecondParameter<typeof customInstance>) => {
  return customInstance<ShopItemBean[]>(
    { url: `/get-items`, method: 'GET' },
    options
  );
};
export type GetItemsResult = NonNullable<Awaited<ReturnType<typeof getItems>>>;
