/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  EntityModelShopItemEntity,
  GetCollectionResourceShopitementityGet1Params,
  PagedModelEntityModelShopItemEntity,
  ShopItemEntityRequestBody,
} from './model';
import { customInstance } from '../boot/axios';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * get-shopitementity
 */
export const getCollectionResourceShopitementityGet1 = (
  params?: GetCollectionResourceShopitementityGet1Params,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<PagedModelEntityModelShopItemEntity | string>(
    { url: `/shopItemEntities`, method: 'GET', params },
    options
  );
};
/**
 * create-shopitementity
 */
export const postCollectionResourceShopitementityPost = (
  shopItemEntityRequestBody: ShopItemEntityRequestBody,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<EntityModelShopItemEntity>(
    {
      url: `/shopItemEntities`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: shopItemEntityRequestBody,
    },
    options
  );
};
/**
 * get-shopitementity
 */
export const getItemResourceShopitementityGet = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<EntityModelShopItemEntity>(
    { url: `/shopItemEntities/${id}`, method: 'GET' },
    options
  );
};
/**
 * update-shopitementity
 */
export const putItemResourceShopitementityPut = (
  id: string,
  shopItemEntityRequestBody: ShopItemEntityRequestBody,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<EntityModelShopItemEntity | void>(
    {
      url: `/shopItemEntities/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: shopItemEntityRequestBody,
    },
    options
  );
};
/**
 * delete-shopitementity
 */
export const deleteItemResourceShopitementityDelete = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<void>(
    { url: `/shopItemEntities/${id}`, method: 'DELETE' },
    options
  );
};
/**
 * patch-shopitementity
 */
export const patchItemResourceShopitementityPatch = (
  id: string,
  shopItemEntityRequestBody: ShopItemEntityRequestBody,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<EntityModelShopItemEntity | void>(
    {
      url: `/shopItemEntities/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: shopItemEntityRequestBody,
    },
    options
  );
};
export type GetCollectionResourceShopitementityGet1Result = NonNullable<
  Awaited<ReturnType<typeof getCollectionResourceShopitementityGet1>>
>;
export type PostCollectionResourceShopitementityPostResult = NonNullable<
  Awaited<ReturnType<typeof postCollectionResourceShopitementityPost>>
>;
export type GetItemResourceShopitementityGetResult = NonNullable<
  Awaited<ReturnType<typeof getItemResourceShopitementityGet>>
>;
export type PutItemResourceShopitementityPutResult = NonNullable<
  Awaited<ReturnType<typeof putItemResourceShopitementityPut>>
>;
export type DeleteItemResourceShopitementityDeleteResult = NonNullable<
  Awaited<ReturnType<typeof deleteItemResourceShopitementityDelete>>
>;
export type PatchItemResourceShopitementityPatchResult = NonNullable<
  Awaited<ReturnType<typeof patchItemResourceShopitementityPatch>>
>;
