/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EntityModelUserEnquiryEntity } from './entityModelUserEnquiryEntity';

export type _PagedModelEntityModelUserEnquiryEntityEmbedded = {
  userEnquiryEntities?: EntityModelUserEnquiryEntity[];
};
