/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Links } from './links';

export interface EntityModelUserEnquiryEntity {
  _links?: Links;
  email?: string;
  enquiryBody?: string;
  enquirySubject?: string;
  fullName?: string;
}
