/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Links } from './links';

export interface EntityModelShopItemEntity {
  _links?: Links;
  category?: string;
  description?: string;
  imagePath?: string;
  material?: string;
  name?: string;
  price?: number;
  quantity?: number;
}
