/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { _PagedModelEntityModelUserEnquiryEntityEmbedded } from './_pagedModelEntityModelUserEnquiryEntityEmbedded';
import type { Links } from './links';
import type { PageMetadata } from './pageMetadata';

export interface PagedModelEntityModelUserEnquiryEntity {
  _embedded?: _PagedModelEntityModelUserEnquiryEntityEmbedded;
  _links?: Links;
  page?: PageMetadata;
}
