/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { _PagedModelEntityModelShopItemEntityEmbedded } from './_pagedModelEntityModelShopItemEntityEmbedded';
import type { Links } from './links';
import type { PageMetadata } from './pageMetadata';

export interface PagedModelEntityModelShopItemEntity {
  _embedded?: _PagedModelEntityModelShopItemEntityEmbedded;
  _links?: Links;
  page?: PageMetadata;
}
