/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PageMetadata {
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
