/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ShopItemEntityRequestBody {
  category?: string;
  description?: string;
  id?: number;
  imagePath?: string;
  material?: string;
  name?: string;
  price?: number;
  quantity?: number;
}
