/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserEnquiryEntityRequestBody {
  email?: string;
  enquiryBody?: string;
  enquirySubject?: string;
  fullName?: string;
  id?: number;
}
